In [15]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [16]:
dataset=pd.read_csv('iris.csv')
dataset

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2   
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
4      5            5.0           3.6            1.4           0.2   
5      6            5.4           3.9            1.7           0.4   
6      7            4.6           3.4            1.4           0.3   
7      8            5.0           3.4            1.5           0.2   
8      9            4.4           2.9            1.4           0.2   
9     10            4.9           3.1            1.5           0.1   
10    11            5.4           3.7            1.5           0.2   
11    12            4.8           3.4            1.6           0.2   
12    13            4.8           3.0            1.4           0.1   
13    14            4.3           3.0            1.1           0.1   
14    15            5.8           4.0            1.2           0.2   
15    16            5.7           4.4            1.5           0.4   
16    17            5.4           3.9            1.3           0.4   
17    18            5.1           3.5            1.4           0.3   
18    19            5.7           3.8            1.7           0.3   
19    20            5.1           3.8            1.5           0.3   
20    21            5.4           3.4            1.7           0.2   
21    22            5.1           3.7            1.5           0.4   
22    23            4.6           3.6            1.0           0.2   
23    24            5.1           3.3            1.7           0.5   
24    25            4.8           3.4            1.9           0.2   
25    26            5.0           3.0            1.6           0.2   
26    27            5.0           3.4            1.6           0.4   
27    28            5.2           3.5            1.5           0.2   
28    29            5.2           3.4            1.4           0.2   
29    30            4.7           3.2            1.6           0.2   
..   ...            ...           ...            ...           ...   
120  121            6.9           3.2            5.7           2.3   
121  122            5.6           2.8            4.9           2.0   
122  123            7.7           2.8            6.7           2.0   
123  124            6.3           2.7            4.9           1.8   
124  125            6.7           3.3            5.7           2.1   
125  126            7.2           3.2            6.0           1.8   
126  127            6.2           2.8            4.8           1.8   
127  128            6.1           3.0            4.9           1.8   
128  129            6.4           2.8            5.6           2.1   
129  130            7.2           3.0            5.8           1.6   
130  131            7.4           2.8            6.1           1.9   
131  132            7.9           3.8            6.4           2.0   
132  133            6.4           2.8            5.6           2.2   
133  134            6.3           2.8            5.1           1.5   
134  135            6.1           2.6            5.6           1.4   
135  136            7.7           3.0            6.1           2.3   
136  137            6.3           3.4            5.6           2.4   
137  138            6.4           3.1            5.5           1.8   
138  139            6.0           3.0            4.8           1.8   
139  140            6.9           3.1            5.4           2.1   
140  141            6.7           3.1            5.6           2.4   
141  142            6.9           3.1            5.1           2.3   
142  143            5.8           2.7            5.1           1.9   
143  144            6.8           3.2            5.9           2.3   
144  145            6.7           3.3            5.7           2.5   
145  146        

In [17]:
dataset.shape

(150, 6)

In [18]:
x=dataset.iloc[:,:4].values
x

array([[  1. ,   5.1,   3.5,   1.4],
       [  2. ,   4.9,   3. ,   1.4],
       [  3. ,   4.7,   3.2,   1.3],
       [  4. ,   4.6,   3.1,   1.5],
       [  5. ,   5. ,   3.6,   1.4],
       [  6. ,   5.4,   3.9,   1.7],
       [  7. ,   4.6,   3.4,   1.4],
       [  8. ,   5. ,   3.4,   1.5],
       [  9. ,   4.4,   2.9,   1.4],
       [ 10. ,   4.9,   3.1,   1.5],
       [ 11. ,   5.4,   3.7,   1.5],
       [ 12. ,   4.8,   3.4,   1.6],
       [ 13. ,   4.8,   3. ,   1.4],
       [ 14. ,   4.3,   3. ,   1.1],
       [ 15. ,   5.8,   4. ,   1.2],
       [ 16. ,   5.7,   4.4,   1.5],
       [ 17. ,   5.4,   3.9,   1.3],
       [ 18. ,   5.1,   3.5,   1.4],
       [ 19. ,   5.7,   3.8,   1.7],
       [ 20. ,   5.1,   3.8,   1.5],
       [ 21. ,   5.4,   3.4,   1.7],
       [ 22. ,   5.1,   3.7,   1.5],
       [ 23. ,   4.6,   3.6,   1. ],
       [ 24. ,   5.1,   3.3,   1.7],
       [ 25. ,   4.8,   3.4,   1.9],
       [ 26. ,   5. ,   3. ,   1.6],
       [ 27. ,   5. ,   3.4,   1.6],
 

In [19]:
y=dataset.iloc[:,-1].values
y

array(['Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versic

In [20]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_y=LabelEncoder()
y=labelencoder_y.fit_transform(y)
#onehotencoder=OneHotEncoder(categorical_features=[0])
#y=onehotencoder.fit_transform(x).toarray()
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [21]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)
x_train

array([[138. ,   6.4,   3.1,   5.5],
       [ 85. ,   5.4,   3. ,   4.5],
       [ 28. ,   5.2,   3.5,   1.5],
       [128. ,   6.1,   3. ,   4.9],
       [133. ,   6.4,   2.8,   5.6],
       [ 60. ,   5.2,   2.7,   3.9],
       [ 19. ,   5.7,   3.8,   1.7],
       [ 84. ,   6. ,   2.7,   5.1],
       [ 62. ,   5.9,   3. ,   4.2],
       [ 93. ,   5.8,   2.6,   4. ],
       [113. ,   6.8,   3. ,   5.5],
       [  3. ,   4.7,   3.2,   1.3],
       [142. ,   6.9,   3.1,   5.1],
       [ 44. ,   5. ,   3.5,   1.6],
       [ 11. ,   5.4,   3.7,   1.5],
       [ 61. ,   5. ,   2. ,   3.5],
       [117. ,   6.5,   3. ,   5.5],
       [145. ,   6.7,   3.3,   5.7],
       [120. ,   6. ,   2.2,   5. ],
       [109. ,   6.7,   2.5,   5.8],
       [ 70. ,   5.6,   2.5,   3.9],
       [136. ,   7.7,   3. ,   6.1],
       [ 57. ,   6.3,   3.3,   4.7],
       [ 81. ,   5.5,   2.4,   3.8],
       [124. ,   6.3,   2.7,   4.9],
       [134. ,   6.3,   2.8,   5.1],
       [107. ,   4.9,   2.5,   4.5],
 

In [22]:
from sklearn.linear_model import LogisticRegression

In [23]:
classifier=LogisticRegression(random_state=0)
classifier.fit(x_train,y_train)

C:\Users\Acer\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Acer\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=0, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [24]:
y_pred=classifier.predict(x_test)
y_pred

array([2, 1, 0, 2, 0, 2, 0, 1, 1, 1, 2, 1, 1, 1, 1, 0, 1, 2, 0, 0, 2, 1,
       0, 0, 2, 0, 0, 2, 2, 0])

In [25]:
#confusion matrix
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred)
cm

array([[11,  0,  0],
       [ 0, 10,  3],
       [ 0,  0,  6]], dtype=int64)